Limpieza dataset "customer_details"

- Eliminar la columna "Unnamed" porque no aporta valor --> **Hecho**
- Poner en minúscula el nombre de todas las columnas --> **Hecho**
- Cambiar el nombre de la columna "NumWebVisitsMonth" por "num_web_visit_month" para que quede más claro. --> **Hecho**
- Crear dos columnas con el mes y el año que el cliente se convirtió en cliente de la empresa --> **Hecho**

In [1]:
# Tratamiento de datos

import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

# ----------

# Exploración de archivos
import sys
sys.path.append('../../../')

#----------

# Funciones personalizadas
from src import sp_cleaning as sc

Cargamos los datos y hacemos una copia

In [2]:
xls = pd.ExcelFile('../../../data/customer-details.xlsx')

df_customer = pd.concat(
    [xls.parse(sheet) for sheet in xls.sheet_names],
    ignore_index=True
)

In [3]:
df_clean = df_customer.copy()

Aseguramos que ha cargado en un único dataframe todos los datos correspondientes a las 3 pestañas del archivo original

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

Elimino la columna "Unnamed" porque no aporta información ni valor al dataframe

In [ ]:
sc.drop_columns(df_clean, ['Unnamed: 0'])

In [ ]:
df_clean.sample(5)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
24743,123004,1,1,2013-12-22,32,2a88c08e-ad17-41ce-9e0e-496b7b120516
40737,28228,0,1,2014-06-18,26,99f227a0-c08a-412e-bca3-d3ebb4bfaa3f
16654,168056,2,1,2012-10-07,18,21d06d01-648a-43b6-a2c1-46579a3386d7
16264,82811,0,0,2012-11-22,4,a8ef094c-1ec9-42bb-85e7-2ebffb3aab01
36515,174171,0,0,2014-11-25,25,1332fa03-82c0-49e5-9233-2d5ed2818131

Cambio a minúscula el nombre de todas las columnas

In [ ]:
df_clean.columns = df_clean.columns.str.lower()

In [ ]:
df_clean.sample(1)

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id
39034,91902,2,0,2014-10-07,5,22242b89-99e5-4e86-af26-d559dbd980ce

Normalizo el texto "numwebvisitsmonth" y lo cambio por "num_web_visits_month" para que quede más claro.

In [ ]:
df_clean = df_clean.rename(columns={'numwebvisitsmonth': 'num_web_visits_month'})

In [ ]:
df_clean.head(1)

,income,kidhome,teenhome,dt_customer,num_web_visits_month,id
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079

Crear dos columnas con el mes y el año que el cliente se convirtió en cliente de la empresa

In [ ]:
df_clean['contact_month'] = df_clean['dt_customer'].dt.month_name().str.lower()
df_clean['contact_year'] = df_clean['dt_customer'].dt.year.astype('Int64')

In [ ]:
df_clean.sample(5)

,income,kidhome,teenhome,dt_customer,num_web_visits_month,id,contact_month,contact_year
42712,134360,2,2,2014-06-10,3,2ad5f398-0147-4ec4-b781-207a09952eee,june,2014
28321,65627,2,1,2013-07-18,12,565be899-64b1-4c1f-a269-ab45b552ea80,july,2013
39090,175489,2,0,2014-05-22,16,c6701bc5-b7f8-4f0b-9ec6-2eccaf15f287,may,2014
13592,79823,2,0,2012-09-11,23,2e0b0989-3e1c-48ac-9efd-de9efc3491f5,september,2012
74,93745,0,2,2012-07-16,27,d3fd430a-83ab-48fb-ad0f-29219a273d56,july,2012